Matrix based


In [1]:
import numpy as np
P=np.array([[1,4],[2,1],[3,2]])
print(P)

[[1 4]
 [2 1]
 [3 2]]


In [3]:
Q=np.array([[2,3],[4,5],[6,5]])
print(Q)

[[2 3]
 [4 5]
 [6 5]]


Addition

In [5]:
c1=np.add(P,Q)
print("Added value of the matrixes are: \n",c1)

Added value of the matrixes are: 
 [[3 7]
 [6 6]
 [9 7]]


Subtract

In [6]:
c2=np.subtract(P,Q)
print("Subtracted value of the matrixes are: \n",c2)

Subtracted value of the matrixes are: 
 [[-1  1]
 [-2 -4]
 [-3 -3]]


Multiplication

In [9]:
a=np.array([[1,2,3],[2,5,6]])
c3=np.dot(P,a)
print("multiplication of matrix is :\n",c3)

multiplication of matrix is :
 [[ 9 22 27]
 [ 4  9 12]
 [ 7 16 21]]


Determinat

In [11]:
c4=np.linalg.det(c3)
print("detrminat of the matrix is:\n",c4)

#smmly np.linalg.inv() will give inverse of a matrix try is ur self.

detrminat of the matrix is:
 -1.776356839400248e-14
